# Generated by Django 6.0.5 on 2026-06-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Site Visit Report', max_length=255)),
                ('schema', models.JSONField(default=list, help_text='List of form field objects')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='visitlog',
            name='report_data',
            field=models.JSONField(blank=True, help_text='Stores the dynamically filled form data as JSON', null=True),
        ),
    ]
