# Generated by Django 6.0.5 on 2026-06-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_tracking', '0002_sitevisitformtemplate_visitlog_report_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='visit_logs/docs/'),
        ),
    ]
