# Generated by Django 6.0.5 on 2026-06-04 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_tracking', '0004_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdHocMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('meeting_title', models.CharField(max_length=255)),
                ('meeting_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location_name', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('current_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('current_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
