# Generated by Django 6.0.5 on 2026-06-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_tracking', '0005_adhocmeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocmeeting',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adhocmeeting',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
