# Generated by Django 6.0.5 on 2026-06-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_tracking', '0006_adhocmeeting_contact_person_adhocmeeting_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocmeeting',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=50),
        ),
    ]
