# Generated by Django 6.0.5 on 2026-06-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_tracking', '0007_adhocmeeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='travel_mode',
            field=models.CharField(blank=True, help_text='e.g., Two-Wheeler, Four-Wheeler, Public Transit', max_length=50, null=True),
        ),
    ]
