# Generated by Django 6.0.5 on 2026-06-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_tracking', '0008_visitlog_travel_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocmeeting',
            name='end_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='adhocmeeting',
            name='end_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='adhocmeeting',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adhocmeeting',
            name='start_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='adhocmeeting',
            name='start_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='adhocmeeting',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
