# Generated by Django 6.0.5 on 2026-06-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_tracking', '0009_adhocmeeting_end_lat_adhocmeeting_end_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocmeeting',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Delayed', 'Delayed')], default='Upcoming', max_length=50),
        ),
    ]
