# Generated by Django 6.0.5 on 2026-06-06 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_tracking', '0010_alter_adhocmeeting_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitlog',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='visitlog',
            name='travel_mode',
        ),
        migrations.AddField(
            model_name='visitlog',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_logs', to='field_tracking.adhocmeeting'),
        ),
    ]
