# Generated by Django 6.0.5 on 2026-06-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_tracking', '0011_remove_visitlog_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocmeeting',
            name='distance_km',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='adhocmeeting',
            name='fuel_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adhocmeeting',
            name='fuel_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
