# Generated by Django 6.0.5 on 2026-06-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_tracking', '0012_adhocmeeting_distance_km_adhocmeeting_fuel_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocmeeting',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='meeting_photos/'),
        ),
    ]
