# Generated by Django 6.0.5 on 2026-06-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_tracking', '0013_adhocmeeting_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOMFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('schema', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_global', models.BooleanField(default=True)),
                ('client_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='adhocmeeting',
            name='report_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adhocmeeting',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Closed', 'Closed'), ('Delayed', 'Delayed')], default='Upcoming', max_length=50),
        ),
    ]
