# Generated by Django 6.0.5 on 2026-06-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_tracking', '0014_momformtemplate_adhocmeeting_report_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('form_type', models.CharField(choices=[('mom', 'Minutes of Meeting (MOM)'), ('site_visit', 'Site Visit Form'), ('other', 'Other Form')], max_length=50, unique=True)),
                ('schema', models.JSONField(default=list, help_text='The JSON array defining the form fields')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='adhocmeeting',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Pending MOM', 'Pending MOM'), ('Closed', 'Closed'), ('Delayed', 'Delayed')], default='Upcoming', max_length=50),
        ),
    ]
