# Generated by Django 6.0.5 on 2026-06-22 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_tracking', '0015_formtemplate_alter_adhocmeeting_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, related_name='assigned_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='is_global',
            field=models.BooleanField(default=True, help_text='If true, available to all employees. If false, only available to assigned_employees.'),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='form_type',
            field=models.CharField(help_text='A unique slug for this form (e.g., site_visit)', max_length=100, unique=True),
        ),
    ]
