# Generated by Django 6.0.5 on 2026-06-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_tracking', '0016_formtemplate_assigned_employees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idle_threshold', models.IntegerField(default=15)),
                ('geo_fence_radius', models.IntegerField(default=50)),
                ('auto_refresh_rate', models.IntegerField(default=30)),
                ('default_map_theme', models.CharField(default='logicon-light', max_length=50)),
            ],
        ),
    ]
