# Generated by Django 6.0.5 on 2026-06-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_tracking', '0017_trackingconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingconfiguration',
            options={'verbose_name': 'Tracking Configuration', 'verbose_name_plural': 'Tracking Configurations'},
        ),
        migrations.AddField(
            model_name='trackingconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trackingconfiguration',
            name='auto_refresh_rate',
            field=models.IntegerField(default=30, help_text='How often live tracking data updates (seconds)'),
        ),
        migrations.AlterField(
            model_name='trackingconfiguration',
            name='geo_fence_radius',
            field=models.IntegerField(default=50, help_text='Default boundary radius for zones (meters)'),
        ),
        migrations.AlterField(
            model_name='trackingconfiguration',
            name='idle_threshold',
            field=models.IntegerField(default=15, help_text='Alert when employee is idle beyond this duration (minutes)'),
        ),
    ]
