# Generated by Django 6.0.5 on 2026-05-25 15:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('territory', models.CharField(max_length=100)),
                ('lastContact', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('value', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('new', 'new'), ('contacted', 'contacted'), ('qualified', 'qualified'), ('proposal', 'proposal'), ('closed-won', 'closed-won'), ('closed-lost', 'closed-lost')], default='new', max_length=50)),
                ('source', models.CharField(max_length=100)),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
