# Generated by Django 6.0.5 on 2026-05-24 10:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('parentCategory', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(choices=[('Physical', 'Physical'), ('Service', 'Service')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50)),
                ('linkedProducts', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Warehouse', 'Warehouse'), ('Branch', 'Branch'), ('Van', 'Van'), ('Store', 'Store')], max_length=50)),
                ('address', models.TextField()),
                ('geoCoordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('gpsEnabled', models.BooleanField(default=False)),
                ('geoFenceEnabled', models.BooleanField(default=False)),
                ('gpsRequired', models.BooleanField(default=False)),
                ('maxCapacity', models.FloatField(default=0)),
                ('currentUtilization', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('productId', models.CharField(max_length=50, unique=True)),
                ('sku', models.CharField(max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('uom', models.CharField(max_length=50)),
                ('sellingPrice', models.FloatField()),
                ('taxCategory', models.CharField(blank=True, max_length=50, null=True)),
                ('trackInventory', models.BooleanField(default=True)),
                ('allowDiscount', models.BooleanField(default=False)),
                ('serialBatchTracking', models.BooleanField(default=False)),
                ('expiryTracking', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('shortCode', models.CharField(max_length=20)),
                ('conversionFactor', models.FloatField(default=1.0)),
                ('baseUnit', models.CharField(blank=True, max_length=50, null=True)),
                ('isBaseUnit', models.BooleanField(default=True)),
                ('inUse', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Distributor', 'Distributor'), ('Dealer', 'Dealer'), ('Reseller', 'Reseller')], max_length=50)),
                ('contactPerson', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('gstId', models.CharField(max_length=50)),
                ('creditLimit', models.FloatField(default=0)),
                ('paymentTerms', models.IntegerField(default=0)),
                ('linkedWarehouse', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
