# Generated by Django 6.0.5 on 2026-05-25 15:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSAlert',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('terminalId', models.CharField(max_length=50)),
                ('terminalName', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('error', 'error'), ('warning', 'warning'), ('info', 'info')], max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.CharField(max_length=50)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='POSTerminal',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Web', 'Web'), ('Mobile', 'Mobile'), ('Hardware', 'Hardware')], max_length=50)),
                ('status', models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('syncing', 'syncing'), ('error', 'error')], max_length=50)),
                ('lastSync', models.CharField(max_length=50)),
                ('todayTransactions', models.IntegerField(default=0)),
                ('todaySales', models.FloatField(default=0)),
                ('errorCount', models.IntegerField(default=0)),
                ('ipAddress', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('operator', models.CharField(max_length=100)),
            ],
        ),
    ]
