# Generated by Django 6.0.5 on 2026-07-07 05:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_in_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_address', models.TextField(blank=True, null=True)),
                ('check_in_photo', models.ImageField(blank=True, null=True, upload_to='attendance_photos/checkin/')),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_address', models.TextField(blank=True, null=True)),
                ('check_out_photo', models.ImageField(blank=True, null=True, upload_to='attendance_photos/checkout/')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
