# Generated by Django 6.0.5 on 2026-05-24 09:52

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=100)),
                ('departmentCode', models.CharField(max_length=50, unique=True)),
                ('parentDepartmentId', models.CharField(blank=True, max_length=50, null=True)),
                ('departmentHeadId', models.CharField(blank=True, max_length=50, null=True)),
                ('trackingEnabled', models.BooleanField(default=False)),
                ('kpiCategory', models.JSONField(blank=True, default=list)),
                ('activeStatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('opsManager', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('completed', 'completed'), ('delayed', 'delayed')], max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('tasksCompleted', models.IntegerField(default=0)),
                ('totalTasks', models.IntegerField(default=0)),
                ('nextMilestone', models.CharField(max_length=200)),
                ('dueDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=100)),
                ('roleCode', models.CharField(max_length=50, unique=True)),
                ('roleType', models.CharField(choices=[('Management', 'Management'), ('Execution', 'Execution')], max_length=50)),
                ('defaultDashboard', models.CharField(max_length=100)),
                ('rolePriority', models.IntegerField()),
                ('activeStatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusMaster',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('statusName', models.CharField(max_length=100)),
                ('tracking', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('All', 'All'), ('Manager Only', 'Manager Only'), ('Admin Only', 'Admin Only')], max_length=50)),
                ('activeStatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=100)),
                ('view', models.BooleanField(default=False)),
                ('create', models.BooleanField(default=False)),
                ('edit', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('approve', models.BooleanField(default=False)),
                ('export', models.BooleanField(default=False)),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=50, unique=True)),
                ('fullName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobileNumber', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('profilePhoto', models.URLField(blank=True, null=True)),
                ('designation', models.CharField(max_length=100)),
                ('reportingManager', models.CharField(blank=True, max_length=50, null=True)),
                ('employmentType', models.CharField(choices=[('Full-time', 'Full-time'), ('Contract', 'Contract')], max_length=50)),
                ('workMode', models.CharField(choices=[('Field', 'Field'), ('Office', 'Office'), ('Hybrid', 'Hybrid')], max_length=50)),
                ('joiningDate', models.DateField()),
                ('trackingEnabled', models.BooleanField(default=False)),
                ('attendanceRequired', models.BooleanField(default=True)),
                ('taskAssignmentAllowed', models.BooleanField(default=True)),
                ('accountStatus', models.BooleanField(default=True)),
                ('departmentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('roleId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role')),
                ('statusId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.statusmaster')),
            ],
        ),
    ]
