# Generated by Django 6.0.5 on 2026-05-25 14:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingManager',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=50)),
                ('employeeName', models.CharField(max_length=200)),
                ('managerId', models.CharField(max_length=50)),
                ('managerName', models.CharField(max_length=200)),
                ('reportingType', models.CharField(choices=[('Direct', 'Direct'), ('Dotted', 'Dotted')], max_length=50)),
                ('effectiveFrom', models.CharField(max_length=50)),
                ('effectiveTo', models.CharField(blank=True, max_length=50, null=True)),
                ('visibilityScope', models.CharField(choices=[('Team', 'Team'), ('Department', 'Department')], max_length=50)),
                ('overrideAccess', models.BooleanField(default=False)),
            ],
        ),
    ]
