# Generated by Django 6.0.5 on 2026-05-30 17:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_registrationrequest_alter_employee_profilephoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationrequest',
            old_name='requestDate',
            new_name='createdAt',
        ),
        migrations.RemoveField(
            model_name='project',
            name='dueDate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='nextMilestone',
        ),
        migrations.RemoveField(
            model_name='project',
            name='opsManager',
        ),
        migrations.RemoveField(
            model_name='project',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tasksCompleted',
        ),
        migrations.RemoveField(
            model_name='project',
            name='totalTasks',
        ),
        migrations.AddField(
            model_name='project',
            name='assignedEmployee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('fileUrl', models.TextField()),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
                ('fileType', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Valid', max_length=50)),
                ('uploadedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('assignedEmployee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.employee')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.project')),
            ],
        ),
    ]
