# Generated by Django 6.0.5 on 2026-05-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_permissionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assignedEmployee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignedEmployee',
        ),
        migrations.AddField(
            model_name='project',
            name='assignedEmployees',
            field=models.ManyToManyField(blank=True, related_name='projects', to='core.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='assignedEmployees',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='core.employee'),
        ),
    ]
