# Generated by Django 6.0.5 on 2026-05-31 08:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_project_assignedemployee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeId',
            field=models.CharField(default=core.models.generate_employee_id, max_length=50, unique=True),
        ),
    ]
