# Generated by Django 6.0.5 on 2026-05-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_employee_employeeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectType',
            field=models.CharField(choices=[('Group', 'Group'), ('Individual', 'Individual')], default='Group', max_length=50),
        ),
    ]
