# Generated by Django 6.0.5 on 2026-06-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_employee_departmentid_alter_employee_roleid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='travelMode',
            field=models.CharField(choices=[('Bike', 'Bike'), ('Scooty', 'Scooty'), ('Car', 'Car')], default='Bike', max_length=50),
        ),
    ]
