# Generated by Django 6.0.5 on 2026-08-03 09:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_geographicnode_employee_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisioningLog',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('action', models.CharField(choices=[('provision', 'Provision'), ('deprovision', 'Deprovision'), ('update', 'Update')], max_length=16)),
                ('logicon_employee_id', models.IntegerField(db_index=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(choices=[('success', 'Success'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='location',
        ),
        migrations.AddField(
            model_name='employee',
            name='current_site_scope',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='employee',
            name='logicon_deployment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='logicon_employee_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.DeleteModel(
            name='GeographicNode',
        ),
    ]
