# Generated by Django 6.0.5 on 2026-08-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_provisioninglog_remove_employee_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoffCode',
            fields=[
                ('code', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
