# Generated by Django 6.0.5 on 2026-05-24 10:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('low_achievement', 'low_achievement'), ('inactive_gps', 'inactive_gps'), ('pending_approval', 'pending_approval'), ('compliance', 'compliance'), ('license_expiry', 'license_expiry'), ('stock_low', 'stock_low')], max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], max_length=50)),
                ('resolved', models.BooleanField(default=False)),
                ('relatedEntityId', models.CharField(blank=True, max_length=50, null=True)),
                ('relatedEntityType', models.CharField(blank=True, choices=[('employee', 'employee'), ('distributor', 'distributor'), ('product', 'product'), ('territory', 'territory'), ('meeting', 'meeting')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTask',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=50)),
                ('taskTitle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('assignedDate', models.DateField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in-progress', 'in-progress'), ('completed', 'completed'), ('overdue', 'overdue')], default='pending', max_length=50)),
                ('completionPercent', models.IntegerField(default=0)),
                ('proofUploaded', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assignedBy', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('internal', 'internal'), ('client', 'client'), ('sales', 'sales'), ('follow-up', 'follow-up')], max_length=50)),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('organizer', models.CharField(max_length=200)),
                ('organizerId', models.CharField(max_length=50)),
                ('attendees', models.JSONField(default=list)),
                ('externalGuests', models.JSONField(default=list)),
                ('location', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('in-person', 'in-person'), ('online', 'online'), ('hybrid', 'hybrid')], max_length=50)),
                ('meetingLink', models.URLField(blank=True, null=True)),
                ('agenda', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(default=list)),
                ('reminder', models.CharField(choices=[('15min', '15min'), ('30min', '30min'), ('1hour', '1hour'), ('none', 'none')], max_length=50)),
                ('recurring', models.CharField(choices=[('none', 'none'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=50)),
                ('approvalRequired', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('rescheduled', 'rescheduled')], default='scheduled', max_length=50)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingEntry',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=50)),
                ('employeeName', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('currentLocation', models.CharField(max_length=200)),
                ('checkInTime', models.DateTimeField()),
                ('checkOutTime', models.DateTimeField(blank=True, null=True)),
                ('travelDistance', models.FloatField(default=0)),
                ('idleTime', models.FloatField(default=0)),
                ('planVsActual', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('idle', 'idle')], max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
