# Generated by Django 6.0.5 on 2026-05-25 15:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEntry',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('employeeName', models.CharField(max_length=200)),
                ('employeeCode', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('scheduledShift', models.CharField(max_length=100)),
                ('actualCheckIn', models.CharField(blank=True, max_length=50, null=True)),
                ('actualCheckOut', models.CharField(blank=True, max_length=50, null=True)),
                ('lateArrival', models.IntegerField(default=0)),
                ('earlyExit', models.IntegerField(default=0)),
                ('totalHoursWorked', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('on-leave', 'on-leave'), ('half-day', 'half-day')], default='present', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GeoFenceAlert',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('employeeName', models.CharField(max_length=200)),
                ('employeeCode', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('currentLocation', models.CharField(max_length=200)),
                ('assignedZone', models.CharField(max_length=200)),
                ('alertType', models.CharField(choices=[('zone-exit', 'zone-exit'), ('idle-breach', 'idle-breach'), ('restricted-entry', 'restricted-entry'), ('boundary-violation', 'boundary-violation')], max_length=50)),
                ('alertTime', models.CharField(blank=True, max_length=50, null=True)),
                ('idleDuration', models.IntegerField(default=0)),
                ('planVsActual', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('online', 'online'), ('idle', 'idle'), ('offline', 'offline')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=50)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=100)),
                ('total', models.IntegerField(default=0)),
                ('used', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=50)),
                ('metricName', models.CharField(max_length=100)),
                ('value', models.FloatField(default=0)),
                ('target', models.FloatField(default=0)),
                ('period', models.CharField(max_length=50)),
            ],
        ),
    ]
