# Generated by Django 6.0.5 on 2026-05-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_attendanceentry_geofencealert_leavebalance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingentry',
            name='reimbursementAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trackingentry',
            name='routePath',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trackingentry',
            name='timeSpentOnSite',
            field=models.FloatField(default=0),
        ),
    ]
