# Generated by Django 6.0.5 on 2026-05-27 06:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_trackingentry_reimbursementamount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWallet',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=50, unique=True)),
                ('balance', models.FloatField(default=0)),
                ('totalEarned', models.FloatField(default=0)),
                ('totalWithdrawn', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=50)),
                ('requestDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
