# Generated by Django 6.0.5 on 2026-05-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_employeewallet_withdrawalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('low_achievement', 'low_achievement'), ('inactive_gps', 'inactive_gps'), ('pending_approval', 'pending_approval'), ('compliance', 'compliance'), ('license_expiry', 'license_expiry'), ('stock_low', 'stock_low'), ('tracking_update', 'tracking_update')], max_length=50),
        ),
    ]
