# Generated by Django 6.0.5 on 2026-05-31 11:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0006_leaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('senderId', models.CharField(max_length=50)),
                ('receiverId', models.CharField(blank=True, max_length=50, null=True)),
                ('groupName', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
