# Generated by Django 6.0.5 on 2026-05-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='readBy',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
